[package]
name = "day-11"
version = "0.1.0"
authors = ["Jacob Meacham <jacob.e.meacham@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
array2d = "0.2.1"